create table coffee (
       id int8 generated by default as identity,
        descricao varchar(255),
        collaborator_id int8,
        primary key (id)
    );
	
create table collaborator (
       id int8 generated by default as identity,
        cpf varchar(255),
        nome varchar(255),
        primary key (id)
    );
 alter table if exists coffee 
       add constraint FKjb81k2jtsvckmoxxccljbkvh6 
       foreign key (collaborator_id) 
       references collaborator;
